.env.example
Database/DatabaseConfig.py
Users/valid_username.py
app.py
requirements.txt
static/css/style.css
templates/base.html
templates/login.html
templates/register.html

This pull request introduces new Register and Login pages for the Beehive project using HTML, CSS, and Python (Flask). The following features have been implemented:
1. **Register Page**
- User registration form with fields for username, email, and password.
- Input validation for correct data formats (e.g., email format, password strength).
- Error messages for user feedback (e.g., existing user, invalid input).
2. **Login Page**
- User login form with fields for username/email and password.
- Validation for correct input data.
- Error messages for incorrect login credentials.
- Added `register.html` and `login.html` templates.
- Created `styles.css` for styling the forms and pages.
- Implemented input validation using HTML5.
- Added error handling and messages for better user experience. …

Created a Register and Login page for Beehive

---

Database/DatabaseConfig.py
app.py
static/css/profile.css
static/css/style.css
templates/profile.html

@pradeeban, Please review this and merge this.

Added: User can able to Upload, Edit and Delete the image

---

Database/DatabaseConfig.py
Users/valid_username.py
app.py
static/css/profile.css
templates/profile.html

@pradeeban, Review it and Merge it.

Made the complete profile for managing the user's image like Edit and Delete

---

.env.example
OAuth/config.py
app.py
requirements.txt
static/css/index.css
templates/index.html
templates/login.html

Hi @pradeeban ,
I have successfully initiated the Google OAuth 2.0 process for the admin login. This implementation will enhance the security and streamline the authentication process for our administrative users by leveraging Google's robust OAuth 2.0 protocol. But the authentication's next process is yet to be developed.
Please let me know if you have any questions or need further details.
Best regards,
@mdxabu

Initiated the Google OAuth 2.0 for the admin login

---

Database/admindatahandler.py
Database/userdatahandler.py
Users/valid_username.py
app.py
static/css/admin.css
static/css/user_profile.css
static/css/userlist.css
templates/admin.html
templates/index.html
templates/signingoogle.html
templates/user_images.html
templates/user_profile.html
templates/users.html

Developed an Admin profile to see the available users.

Add: Developed the admin profile, view users

---

README.md

- Fixed the broken link in setup.md.
- Fixed the broken link in contributing.md.
- Both links are now functional, providing proper redirection to their respective pages.

Fixed Broken Links in Documentation

---

CODE_OF_CONDUCT.md
DOCS/contributing.md
static/css/index.css
static/css/userlist.css

This pull request introduces the following changes:
- Updated the CONTRIBUTING.md file to provide clearer guidelines for contributing to the project.
- Added a Code of Conduct to ensure a respectful and inclusive environment for all contributors.
These changes aim to foster better collaboration and create a welcoming space for contributors.

Add Code of Conduct and Update CONTRIBUTING.md

---

static/css/index.css
static/css/userlist.css

This pull request introduces the following changes:
- Updated the CONTRIBUTING.md file to provide clearer guidelines for contributing to the project.
- Added a Code of Conduct to ensure a respectful and inclusive environment for all contributors.
These changes aim to foster better collaboration and create a welcoming space for contributors.

Add Code of Conduct and Update CONTRIBUTING.md for Dev Branch

---

README.md

This pull request modifies the README file to reflect updates and changes made in the dev branch. The following changes were made:
- Updated the project setup instructions for the dev environment.
- Additional notes on libraries and configuration requirements were added.
- Clarified section on development workflow and branch structure.
- Fixed typos and improved readability in several sections.

Update README for Dev Branch

---

.github/PULL_REQUEST_TEMPLATE.md

- Added a Pull Request Template to the repository.
- This template helps standardize the process for submitting pull requests and ensures that essential information is included in every PR.

Added the Pull Request Template

---

.github/PULL_REQUEST_TEMPLATE.md

Added the Pull Request Template for DEV branch

---

.github/workflows/check-merge-conflicts-on-comment.yml

Added conflict checker action for pull requests

---

.github/workflows/check-merge-conflicts-on-comment.yml

Added a Mere Conflict finder Action

---

client_secret_example.json
static/css/profile.css
templates/profile.html

Solves issue #47 
Added responsiveness to the Profile page to increase readability and ensure alignment
before:-
after:-
**Checklist:**

Add Responsiveness to the Profile Page

---

client_secret_example.json
static/css/profile.css
static/css/style.css
templates/profile.html

Made the Login,register and profile page responsive to ensure alignment and readability on phones.
**Checklist:**

Add Responsiveness in Login Page, Register Page and profile Page

---

Database/userdatahandler.py
app.py
client_secret_example.json
static/css/profile.css
templates/profile.html
templates/user_images.html

**In reference to** _Originally posted by @pradeeban in https://github.com/KathiraveluLab/Beehive/discussions/3#discussioncomment-12051509_
**Solves issue** #50 
This PR introduces the ability for users to **record a voice note** along with their uploaded images. The recorded voice note is saved and displayed with a **speaker icon** for admins to listen to.  
**Users can record a voice note** while uploading an image.  
Audio is saved in `static/uploads/`.  
**Admins can see a speaker icon** next to images with audio.  
**Clicking the speaker icon plays the recorded voice note.**  
**Ensures smooth UI/UX experience with mobile responsiveness.**  
---
This is an example of how this happens when user records his VN he can also reset it. …

Add voice note when uploading image

---

Database/userdatahandler.py
app.py
client_secret_example.json
static/css/profile.css
templates/profile.html
templates/user_images.html

Solves issue #55 
This PR is in continuation with #62 
This PR enhances the **upload functionality** by adding: 
**Loader animation** on the upload button while the file is being uploaded  
**Proper form validation** before submission (prevents empty fields from submitting)   
---
User selects a file, enters a **title & description**, then clicks **Upload**  
The **button animation starts**, and the form **validates required fields**  
If **fields are missing**, the form **won’t submit & shows validation errors**  
If **everything is correct**, the form submits  
---
https://github.com/user-attachments/assets/9ea6c2df-8418-4a45-ba2d-2c46b349fe2f
Would love a review & feedback! 
**Checklist:**

Add Loader while uploading images

---

static/css/footer.css
static/css/profile.css
templates/admin.html
templates/footer.html
templates/profile.html
templates/user_images.html
templates/user_profile.html

@pradeeban @mdxabu 
similar to PR #67, which was for dev branch
Added footer and ensured that it is responsive.
**Checklist:**

Add Footer - Main

---

static/css/footer.css
static/css/profile.css
templates/admin.html
templates/footer.html
templates/profile.html
templates/user_images.html
templates/user_profile.html
templates/users.html

Solves issue #56 
Added a footer for all pages and ensured responsiveness.
Added links of github in About,documentation and contribution buttons
**Checklist:**

Add Footer

---

app.py
templates/profile.html
templates/user_images.html

Solves issue #65 
Added a thumbnail folder so that when we upload pdfs,create the first page of the pdf as a thumbnail to be displayed.
On clicking on the thumbnail so that full pdf can be seeen using iframe.
https://github.com/user-attachments/assets/909c3e51-7438-4f49-ae2a-d15ea39f5bd8
Added this for admin dashboard also
**Checklist:**

Add PDF preview

---

README.md

Add a workflow/architecture for new contributors.
This is further to be changes when we migrate to a react frontend and move to production.
**Checklist:**

Update README.md with workflow

---

static/css/index.css
templates/index.html

fix : #109 
this PR modifies index.html for better UX.

better UX for index.html

---

Database/admindatahandler.py
Database/userdatahandler.py
app.py
static/css/admin.css
static/css/profile.css
templates/admin.html
templates/profile.html

This PR implements profile photo functionality for both users and administrators. Users and admins can now upload, display, and update their profile pictures through an in-display sidebar interface.
- Extended user and admin collection schema to support profile photo storage
- Added photo database handlers in userdatahandler.py and admindatahandler.py .
- Created upload_profile_photo() and upload_admin_profile_photo route to process user and admin photo uploads respectively.
- Updated admin.html and profile.html template to display profile photos
- Added CSS styling to admin.css and profile.css.
- Profile photos are stored in static/uploads/profile/ directory
- Consistent naming convention: username_profile.ext for users and admin_{google_id}_profile.ext for admins
- Sidebar opens on …

Add Profile Photo Display with Sidebar for User & Admin

---

app.py

Fixes minor bug on profile image upload
Add the code to create a directory for first time when uploading images which solves issue #123 
**Checklist:**

Issue with profile-image upload

---

DOCS/setup.md

This PR adds documentation about the required directory structure for proper application functionality. It clarifies which upload directories are necessary for the application to operate correctly and how they're handled during runtime.
**Checklist:**

Add Essential Upload Directories Documentation

---

DOCS/setup.md
Database/admindatahandler.py
Database/userdatahandler.py
OAuth/config.py
app.py
static/css/style.css
templates/google_register.html
templates/login.html

This PR integrates google SSO for users and  improves admin authentication by ensuring consistency across Google SSO and traditional logins. It also fixes environment variable loading issues and enhances error handling.
(As Discussed in #84 )
- Admin Authentication: Improved admin detection via MongoDB and ALLOWED_EMAILS.
- Google SSO: Extended for users, added admin redirection & first-time registration.
- Error Handling: Prevented KeyErrors, improved session management, and added debug logs.
- Environment Fixes: Proper loading & parsing of ADMIN_EMAILS.
- Regular & admin users can log in via traditional or Google SSO.
- Admin access verified via google_id or ALLOWED_EMAILS.
- Unauthorized admin attempts redirected to a 403 error page.
**Checklist:**

Google SSO integration for users and enhance admin authentication Implement 

---

static/css/userlist.css
templates/users.html

Added filter by name, email and filter by date options for admin table on the UI, ensured responsive UI
**Checklist:**

Add filtering option for admin table

---

static/css/style.css
templates/login.html

Made corrections to the PR #130 to add an eye-icon button for password.
**Checklist:**

Added eye-icon upgrade

---

DOCS/login-workflow.md

This PR adds a document for the robust authentication system with clear admin and user login flows. Admins and users can now log in via traditional credentials and Google SSO ,and will be automatically redirected to their respective dashboards according to their email Ids.
**Checklist:**

Add comprehensive authentication workflow documentation

---

static/css/admin.css
static/css/footer.css
static/css/profile.css
static/css/signin.css
static/css/style.css
static/css/user_profile.css
static/css/userlist.css

Enhanced the background of all the pages of the website to match the logo of Beehive and also fixed the footer.
**Older version**
**Checklist:**

Enhanced Background

---

app.py
routes/__init__.py
routes/home.py

* first step to refactor app.py
* created routes to collect all routes in one place and make app.py smaller
* moved the first route from app.py to routes dir 
* we will build on top of that further 
@pradeeban please have a look

created routes dir to refactor app.py

---

static/css/footer.css
static/css/profile.css
templates/profile.html

Fixed minor bugs- realign footer and align the upload option button
**Enhance Logout Button**
https://github.com/user-attachments/assets/d502ff2e-ee6a-4bca-898a-675f3b24a3f8
**Checklist:**

Enhance Logout Button and realigned footer

---

Database/userdatahandler.py
app.py
templates/forgotpassword.html
templates/login.html
templates/register.html

**solves #102** 
Added the security question feature where user can select his security question at time of registering.
if they forget the pwd they can answer the security question and if its right they can change the pwd and login
**with this will add the manual admin pwd reset option** 
**Checklist:**

Add forgot password

---

static/css/admin.css
templates/admin.html

Changes:
- Removed the logout button from the main admin page.
- Added the logout button (Similar to what we have in the profile page implemented) inside the admin sidebar, ensuring consistency with the profile sidebar.
- Finally Centered the "View Users" (As of now, can be alligned as per need in future, have marked accordingly)button for better alignment across all devices after all the changes.
This improves UI alignment and keeps the logout functionality in a structured location.
**Checklist:**

Logout Button Relocation and UI Enhancements

---

Database/admindatahandler.py
app.py
auth/auth.py

* Moved the role_required decorator from app.py to auth/auth.py for better modularity.
* Added __init__.py in the Database directory to make it a package, enabling easier imports in other directories.

moved role_required to auth

---

README.md

This PR is an update to #153 , now directing the changes to the dev branch as per the repository guidelines. The content remains the same, ensuring that new contributors are informed about the active branches.
**Checklist:**

Update PR #153 to Target dev Branch

---

static/css/admin.css
static/css/profile.css
templates/admin.html

User Side:
- Centered the "Click to Upload or Drag & Drop Anywhere" button.
- Aligned Beehive text with the logo.
Admin Side:
- Implemented a sticky footer to keep it at the bottom regardless of content height.
- Adjusted Beehive Logo to the left and added a "Beehive" text.
- Centered admin_name and ADMIN badge properly accordingly after the changes.
A.User Page:
B.Admin Page:
A.User Page:
**Checklist:**

UI Fixes for Alignment & Sticky Footer

---

app.py
static/security_questions.json
templates/forgotpassword.html
templates/register.html

wrt discussions on PR #146, in continuation with adding the reqd. features.
1) put the security questions in a json file
2) let the user add a custom question as its securitty question
upcoming PRs will have 3 security questions, then manual admin reset option followed by letting users to choose if they in future want to reset their pwd or let admins only reset the pwd
**Checklist:**

Add security questions.json and custom question option

---

app.py
routes/__init__.py
routes/register.py
templates/login.html
templates/register.html

* moved /register and /register/google routes to register.py file
* also updated template files to use the new routes correctly using their blueprints

moved register routes to register.py

---

app.py
static/css/userlist.css
templates/users.html

Added Manual Password reset option as suggested by Pradeeban so that admins can directly change the password for users.
These functionalities are also beneficial and applicable once we move to a better auth and a better UI.
**Checklist:**

Add admin password reset option

---

app.py
routes/__init__.py
routes/login.py
templates/index.html
templates/login.html
templates/register.html

**moved ```\login``` route from app.py to login.py inside routes dir**
**created a new blueprint for that**
**modified all templates that use login route to adjust to that modification**

moved login route from app.py to login.py

---

app.py
routes/__init__.py
routes/logout.py
templates/profile.html

**moved logout from app.py to logout.py**
**updated templates accordingly**

moved logout route from app.py to logout.py

---

tests/conftest.py
tests/test_login.py
tests/test_logout.py

As we are currently refactoring and adding features, it's essential to establish a comprehensive test suite.
These tests will replace manual testing, ensuring reliability and easier maintenance of the code.

started building tests dir

---

app.py
routes/__init__.py
routes/login.py
routes/profile.py

* moved profile route from app.py to profile.py
* created a new blueprint for profile.py
* modified login.py to reference the profile template using the new way

moved profile route from app.py to profile.py

---

tests/test_auth.py

Added 2 tests for checking the /register route and for checking the password validation 
Both are working fine 
**Checklist:**

Add Auth tests

---

app.py
routes/__init__.py
routes/change_email.py
routes/change_password.py
routes/change_username.py
templates/profile.html

**moved the following routes change_password, change_email, change_username**
from app.py to their respective files
```change_password.py```  ```change_email.py```  ```change_username.py```
and modified profile template accordingly

refactored 3 routes change_username, change_password, change_email

---

tests/test_index.py
tests/test_routes.py

Removed the index_test file and added a Route testing file which will have all the tests for routes. Included some Route tests.
All passed
**Checklist:**

Add testing file for Routes

---

DOCS/testing.md
tests/test_index.py
tests/test_routes.py

Add a documentation for new contributors so that they can run the test cases.
**Checklist:**

Add Testing Documentation

---

.github/workflows/code-review.yaml

Used Gemini for reviewing code and finding issues if any in the PRs.
we have to comment /review for workflow to run.
Tested it on my local repo
**Checklist:**

Add a code review Bot 

---

.github/workflows/greetings.yaml

The bot displays a greeting message to new first time contributors on issues and PRs
**Checklist:**

Add a Greetings bot for first time contributors

---

app.py
usersutils/allowd_files.py
usersutils/generate_thumbnail.py

**Description:**
Moved some utils from app.py
- ```allowed_file``` from app.py to allowed_file.py
- ```generate_pdf_thumbnail``` to generate_thumbnail.py```

Refactored some utils from app.py to usersutils

---

.github/workflows/code-review.yaml

Updated the command for invoking the review bot.
**Checklist:**

Update code-review.yaml with updated command

---

app.py
routes/__init__.py
routes/delete_image.py
routes/upload.py
routes/upload_profile_photo.py
templates/profile.html

**Description:**
- moved upload_profile_photo from app.py 
- also handled some missing of part of previously refactored code in upload route and removed the duplicate code from app.py
- moved delete_image from app.py
- registered blueprints
- modified profile template accordingly

moved upload_profile_photo and delete_image from app.py

---

app.py
database/admindatahandler.py
database/userdatahandler.py
frontend/src/pages/admin/Users.tsx

Implemented user table as a api call to clerk dashboard.
**Checklist:**

Implement user table in admin Dashboard

---

app.py
database/userdatahandler.py
frontend/src/pages/admin/UserUploads.tsx
frontend/src/pages/admin/Users.tsx

Changed the logic to store images with user_id.
Replicated the same design in the revamped Ui for image uploads by each user.
**Checklist:**

Admin table for user uploads

---

app.py

Removed routes which are no longer needed for admin auths because clerk hai support for all of this
**Checklist:**

Removed unused routes in app.py

---

app.py
database/databaseConfig.py
database/userdatahandler.py
frontend/src/layouts/AdminLayout.tsx
frontend/src/pages/Upload.tsx

Add notification feature that shows notification to admin when image is uploaded by user. Added schema in mongoDB for the same. 
**Checklist:**

Add notification system for admin on image uploads

---

Routes/adminRoutes.py
app.py
database/databaseConfig.py
database/userdatahandler.py
frontend/src/components/ChatDrawer.tsx
frontend/src/layouts/AdminLayout.tsx
frontend/src/layouts/MainLayout.tsx

Add messaging system using polling method. This enables users to send messages to admin and vice versa.
Add message scheme in mongoDB.
**Checklist:**

Add chat messaging system between user and admin

---

frontend/src/components/ChatDrawer.tsx
frontend/src/layouts/AdminLayout.tsx
frontend/src/layouts/MainLayout.tsx
frontend/src/pages/admin/Users.tsx

Ensured Responsive for all screens, and introduced hamburger in navbar for very small screens.

Add responsive

---

database/userdatahandler.py
frontend/src/pages/admin/Dashboard.tsx

Fixed minor bugs in the 2 routes on admin dashboard.

Fix recent upload,get stat route on admin dashboard
